# Backend service
[[services]]
name = "zara-backend"
root = "server"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm install --production"

[services.deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[services.env]
NODE_ENV = "production"
PORT = "$PORT"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"

# Frontend service
[[services]]
name = "zara-frontend"
root = "frontend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[services.env]
NODE_ENV = "production"
PORT = "$PORT"